# Generated by Django 5.1 on 2026-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop0c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=16, verbose_name='商品色'),
        ),
    ]
